# Direções de interpretação. Cada par: (início literal do parágrafo, marcação).
# A marcação entra num parágrafo próprio, imediatamente antes da fala.

BLOCO3 = [
    ('E um paciente me disse, logo na primeira sessão',
     '{OLHAR PARA A PLATEIA | DESACELERAR}'),
    ('Eu nunca esqueci essa frase.',                      '{PAUSA 2s}'),
    ('Ela não demonstrava equivalência',                  '{FIRME}'),
    ('Eu realizei entrevistas semiestruturadas',
     '{RITMO + | é o método: dizer com segurança, sem soar defensiva}'),
    ('Feita essa delimitação, eu organizei',              '{NÃO CORRER | os três eixos organizam tudo o que vem}'),
    ('Nos quatro relatos, o uso apareceu antes de dormir','{ÊNFASE nos números}'),
    ('Uma participante disse:',                           '{ACOLHEDOR | a fala é dela, não sua}'),
    ('Reparem que não há aí uma decisão planejada',       '{PAUSA 1s | DESACELERAR — é interpretação, não dado}'),
    ('Vamos para o segundo eixo',                         '{NÃO CORRER}'),
    ('Esse é um ponto central dos achados',               '{FIRME | SUSTENTAR A FRASE}'),
    ('Nas palavras bastante coloquiais',                  '{ACOLHEDOR | sem imitar o participante}'),
    ('Ele não está usando um conceito técnico.',          '{PAUSA 1s | volta a ser você falando}'),
    ('Uma participante contou que o WhatsApp',            '{DESACELERAR}'),
    ('Mas o próprio uso também produzia',                 '{ÊNFASE nos números}'),
    ('E aqui apareceu um achado que eu considero',        '{DESACELERAR | tom de descoberta — não entregue o sentido antes}'),
    ('Ou seja: uma mesma estratégia de autocontrole',     '{PAUSA 2s}'),
    ('E a fala mais forte desse eixo foi esta:',          '{OLHAR PARA A PLATEIA}'),
    ('Reconhecimento do prejuízo.',                       '{RITMO +}'),
    ('Querer interromper não significava',                '{BAIXAR LEVEMENTE O TOM | SUSTENTAR A FRASE}'),
    ('Um processo que me ajudou a compreender',           '{NÃO CORRER | conceito}'),
    ('Por fim, chamou atenção o fato',                    '{PAUSA 1s}'),
    ('Uma das participantes resumiu essa experiência',    '{DESACELERAR | OLHAR PARA A PLATEIA}'),
    ('A busca contínua por mais.',                        '{SILÊNCIO 3s}'),
    ('O tempo de tela mostra',                            '{FIRME | ÊNFASE em QUANTO e em POR QUE}'),
    ('Quando existe sofrimento ou prejuízo',              '{DESACELERAR | é a pergunta que abre o próximo bloco}'),
]

BLOCO4 = [
    ('Para concluir, eu quero voltar ao rapaz',           '{ACOLHEDOR | DESACELERAR — tom reflexivo}'),
    ('E ele dizia:',                                      '{OLHAR PARA A PLATEIA}'),
    ('Ao redor dele, aquilo era entendido',               '{SILÊNCIO 3s}'),
    ('Mas essas palavras julgavam',                       '{FIRME | a força vem da precisão, não do volume}'),
    ('Hoje, o uso problemático de redes sociais',         '{PAUSA 1s}'),
    ('nem todo uso intenso constitui um transtorno;',     '{ÊNFASE no contraste entre as duas direções}'),
    ('Por isso, diante de um comportamento repetitivo',   '{FIRME | está entregando uma ferramenta}'),
    ('O que costuma acontecer antes?',                    '{NÃO CORRER}'),
    ('O que esse comportamento oferece ou ajuda a afastar?', '{NÃO CORRER}'),
    ('É justamente aqui que a vinheta de Rafael',         '{DESACELERAR | agora é história clínica, não conceito}'),
    ('Até que disse:',                                    '{OLHAR PARA A PLATEIA | sem voz de personagem}'),
    ('As pessoas estavam em casa',                        '{PAUSA 2s}'),
    ('a experiência de solidão dentro do lugar',          '{DESACELERAR | SUSTENTAR A FRASE}'),
    ('Quais custos esse comportamento está produzindo?',  '{FIRME | NÃO CORRER}'),
    ('O risco define a prioridade',                       '{FIRME | dizer como algo incontestável, sem dramatizar}'),
    ('E a quarta pergunta é:',                            '{SILÊNCIO 3s}'),
    ('Se esse comportamento for reduzido ou interrompido','{DESACELERAR | NÃO CORRER — a mais profunda das quatro}'),
    ('Se o álcool aliviava a solidão de Rafael',          '{pergunta real, feita por ele e não sobre ele}'),
    ('Mas também precisamos ampliar o repertório',        '{RITMO + | a energia começa a crescer}'),
    ('Novas respostas precisam ser praticadas',           '{DESACELERAR}'),
    ('Às vezes, o psiquiatra encontrará',                 '{ACOLHEDOR | OLHAR PARA DIFERENTES PONTOS DA PLATEIA}'),
    ('Se vocês saírem daqui com uma ideia',               '{PARAR | OLHAR PARA A PLATEIA | daqui até o fim, sem consultar o roteiro}'),
    ('Porque o comportamento que vemos pode ser',         '{PAUSA 2s | DESACELERAR}'),
    ('Porque o cuidado não termina',                      '{PAUSA 2s | SUSTENTAR A FRASE}'),
    ('Ele se sustenta quando a vida se torna',            '{BAIXAR LEVEMENTE O TOM | mais lento que tudo o que veio antes}'),
    ('Obrigada.',                                         '{SILÊNCIO 3s — SUSTENTAR O OLHAR}'),
]
