# Marcações cênicas de Abertura, Bloco 1 e Bloco 2.
# Chave = início literal do parágrafo ORIGINAL antes do qual a marcação entra.
# ('texto da marcação', essencial_no_palco)

ABERTURA = [
    ('Boa tarde pessoal',               '{TOM CONVERSACIONAL | OLHAR ABERTO PARA A PLATEIA}', False),
    ('Essa frase foi dita por um paciente de 19 anos', '{SILÊNCIO 2s}', True),
    ('Em outro contexto clínico',       '{OLHAR | DESACELERAR}', True),
    ('Os dois relatos colocam diante',  '{SILÊNCIO 2s}', True),
    ('"O que nós estamos enxergando',   '{FIRME}', True),
    ('→ Estamos apenas diante de uma',  '{PAUSA 1s | UMA PERGUNTA DE CADA VEZ, SEM CORRER}', True),
    ('Do que é que estamos diante',     '{PAUSA 1s}', False),
    ('Meu nome é Camila Freitas',       '{SILÊNCIO 2s | TOM CONVERSACIONAL — apresentação pessoal, sem pressa}', True),
    ('Quando aproximo esses dois fenômenos', '{FIRME — delimitação ética; dizer com segurança, não como desculpa}', True),
    ('Porque, na prática clínica',      '{PAUSA 1s}', False),
    ('Então, para começar',             '{DESACELERAR | OLHAR}', True),
    ('Para compreender um uso que se tornou problemático', '{FIRME | VOZ DESCENDENTE}', True),
]

BLOCO1 = [
    ('↳ QUANTO a pessoa usa?',          '{RITMO + | TRÊS PERGUNTAS EM SEQUÊNCIA}', False),
    ('Mas, sozinhas, essas perguntas',  '{DESACELERAR}', True),
    ('Por que continuar, apesar dos prejuízos', '{FIRME | PAUSA 1s}', True),
    ('Vamos pensar nessa história',     '{TOM CONVERSACIONAL — começa a narrativa}', False),
    ('Só que... com o tempo',           '{DESACELERAR}', False),
    ('POR QUE SERÁ QUE ISSO ACONTECE?', '{OLHAR | PAUSA 1s}', True),
    ('Pode vir PRAZER',                 '{RITMO +}', False),
    ('A sensação pode chegar SEM DEMORA','{ÊNFASE NA VELOCIDADE}', True),
    ('Já outras formas de buscar',      '{CONTRASTE — desacelerar deliberadamente aqui}', True),
    ('E aí pode existir a dúvida',      '{TOM DE PERGUNTA GENUÍNA — antecipar a dúvida da plateia}', False),
    ('Portanto, a diferença NÃO ESTÁ',  '{FIRME}', True),
    ('↳ na RAPIDEZ com que esses efeitos', '{RITMO + | LISTA — não arrastar}', False),
    ('Ao longo do tempo, essa DIFERENÇA','{DESACELERAR}', False),
    ('É aqui que um conceito da Análise','{FIRME | ENTRADA DO CONCEITO — falar com autoridade}', True),
    ('O comportamento é selecionado',   '{DESACELERAR | PAUSA 1s}', True),
    ('Vamos imaginar a seguinte situação','{TOM CONVERSACIONAL | EXEMPLO CONCRETO}', False),
    ('DIA ESTRESSANTE → USO DE SUBSTÂNCIA', '{FIRME | MARCAR A SETA COM A MÃO}', True),
    ('Se isso acontece repetidamente',  '{PAUSA 1s}', False),
    ('Lembram que eu falei que, no começo', '{OLHAR — retomar o fio com a plateia}', True),
    ('Assim, isto significa que o uso pode começar', '{DESACELERAR}', False),
    ('Retomando um dos casos clínicos', '{TOM HUMANO E CONTIDO | DESACELERAR — caso clínico}', True),
    ('Esse entendimento, sozinho',      '{VOZ DESCENDENTE | PAUSA 1s}', True),
    ('Agora, pensem por alguns segundos','{PARAR | OLHAR | PERGUNTA REAL À PLATEIA}', True),
    ('Muitas vezes, aparece a ideia de FALTA', '{SILÊNCIO 2s}', True),
    ('“Mas se a pessoa quer parar de beber', '{MUDAR LEVEMENTE O TOM — são falas de outros, não suas}', True),
    ('Ou seja, isso chega a ser tratado','{FIRME}', False),
    ('Vocês já sabem que o fenômeno',   '{TOM DE CUMPLICIDADE COM A PLATEIA}', True),
    ('“Como esse comportamento foi ganhando força?', '{RITMO + | TRÊS PERGUNTAS}', False),
    ('A partir daí, uma nova pergunta', '{DESACELERAR | OLHAR}', True),
    ('Que FUNÇÃO esse uso passou a cumprir', '{FIRME | VOZ DESCENDENTE | PAUSA 1s}', True),
]

BLOCO2 = [
    ('1. O que esse uso FAZ pela pessoa', '{FIRME | PAUSA 1s}', True),
    ('De algum modo, naquele momento',  '{DESACELERAR}', False),
    ('Quando aquilo que aparece depois','{TOM PROFISSIONAL — conceito entrando}', False),
    ('“Negativo” aqui não significa ruim', '{ÊNFASE — desfazer o mal-entendido comum}', True),
    ('Um paciente descreveu o início do uso', '{OLHAR | DESACELERAR — relato}', True),
    ('Nesse relato, portanto',          '{PAUSA 1s}', True),
    ('O USO, muitas vezes, é FORTALECIDO', '{FIRME}', False),
    ('Agora, pensem em duas pessoas',   '{TOM CONVERSACIONAL | PEDIR QUE IMAGINEM}', True),
    ('Mas a formulação clínica seria a mesma?', '{PARAR | PERGUNTA REAL}', True),
    ('Provavelmente não.',              '{SILÊNCIO 2s}', True),
    ('Isso não significa que todo comportamento', '{FIRME — ressalva importante}', True),
    ('Em muitas trajetórias, o uso começa', '{DESACELERAR — a virada da trajetória}', True),
    ('O uso vai se organizando menos',  '{ÊNFASE NO CONTRASTE | PAUSA 1s}', True),
    ('Mas a tolerância não explica tudo','{FIRME}', False),
    ('O mesmo paciente descreveu essa mudança', '{OLHAR | DESACELERAR — mesmo paciente}', True),
    ('Do ponto de vista da formulação', '{SILÊNCIO 2s}', True),
    ('Menor acesso à consequência',     '{RITMO + | DUAS DIFICULDADES}', False),
    ('Nesses momentos, pode ficar mais difícil', '{DESACELERAR}', False),
    ('É por isso que PARAR pode deixar','{FIRME | PAUSA 1s}', True),
    ('Tem uma fala que traduz isso',    '{PARAR | OLHAR | DESACELERAR — a fala mais forte do bloco}', True),
    ('O uso não resolve esses problemas','{SILÊNCIO 2s}', True),
    ('Por isso, o uso pode funcionar como uma solução', '{VOZ DESCENDENTE}', False),
    ('Um comportamento pode continuar cobrando', '{PAUSA 1s}', False),
    ('A interrupção ou a redução do uso','{FIRME — não minimizar risco diante de psiquiatras}', True),
    ('Pensem em uma pessoa que permaneça', '{TOM CONVERSACIONAL | PEDIR QUE IMAGINEM}', True),
    ('Qual é a informação clínica que a abstinência', '{PARAR | PERGUNTA REAL}', True),
    ('Ela não nos diz se a pessoa desenvolveu', '{SILÊNCIO 2s}', True),
    ('A internação pode ser absolutamente', '{FIRME | OLHAR — reconhecer o valor da internação}', True),
    ('Se, durante o cuidado',           '{DESACELERAR}', False),
    ('AMPLIAR O REPERTÓRIO',            '{FIRME | PAUSA 1s}', True),
    ('Ajudar a pessoa a reconhecer as situações', '{RITMO + | QUATRO ITENS, ENERGIA CRESCENTE}', False),
    ('Então, a partir de tudo isso',    '{DESACELERAR}', False),
    ('“O que esse uso oferece?',        '{UMA PERGUNTA DE CADA VEZ | NÃO CORRER}', True),
    ('Até aqui, eu falei sobre como essa lógica', '{PAUSA 1s | TRANSIÇÃO — mudar de assunto com clareza}', True),
    ('A próxima pergunta, então, é:',   '{OLHAR | VOZ DESCENDENTE}', True),
]
